/**
 * Vela — Multi-Year Roth Conversion Pipeline
 *
 * The single-year optimizer answers "what do I withdraw this year." This module
 * answers the question underneath it: over the years between retiring and
 * Medicare, how much can be moved from a Traditional IRA into a Roth without
 * pushing MAGI past the subsidy target — and when does each conversion become
 * accessible.
 *
 * The mechanic being modelled
 * ---------------------------
 * A Roth conversion is taxable income in the year it happens, so it counts
 * toward MAGI and therefore competes directly with the ACA subsidy. Each year
 * there is a *headroom*: the gap between the MAGI the withdrawal plan already
 * generates and the MAGI target. Converting into that headroom is close to free
 * — it costs subsidy only if it overshoots.
 *
 * Each converted amount is subject to the five-year rule: it can be withdrawn
 * penalty-free five tax years after the conversion (or at 59½, whichever comes
 * first). So a ladder started at 50 begins paying out at 55. That timing is the
 * whole point of laddering, and it is what the `accessibleIn` field tracks.
 *
 * ASSUMPTIONS — all explicit, all overridable via PipelineAssumptions.
 * These are projections, not predictions. Every figure this module produces
 * depends on inputs nobody can know in advance (future returns, future FPL
 * levels, future premium costs, and whether current subsidy rules persist).
 * Present the output as modelling, never as a forecast.
 */

import {
  calculateACASubsidy,
  type UserProfile,
} from "./optimizer";

/** Age at which Medicare eligibility begins, ending the ACA subsidy question. */
export const MEDICARE_AGE = 65;

/** Years before a converted amount is accessible penalty-free. */
export const ROTH_SEASONING_YEARS = 5;

/** Age at which the early-withdrawal penalty no longer applies. */
export const PENALTY_FREE_AGE = 59.5;

export interface PipelineAssumptions {
  /** Nominal annual growth on invested balances. */
  growthRate: number;
  /** Annual increase applied to spending and to FPL thresholds. */
  inflationRate: number;
  /**
   * MAGI target as a percentage of FPL. 175% sits below the 250% cost-sharing
   * reduction limit and well under the 400% cliff, matching the single-year
   * optimizer's target.
   */
  targetFplPercentage: number;
  /** Effective federal rate applied to conversion income, for tax-cost display. */
  effectiveTaxRate: number;
}

export const DEFAULT_ASSUMPTIONS: PipelineAssumptions = {
  growthRate: 0.05,
  inflationRate: 0.025,
  targetFplPercentage: 175,
  effectiveTaxRate: 0.12,
};

/** 2026 Federal Poverty Level, inflated forward for later projection years. */
const FPL_2026: Record<number, number> = {
  1: 15650,
  2: 21150,
  3: 26650,
  4: 32150,
  5: 37650,
  6: 43150,
  7: 48650,
  8: 54150,
};

export interface PipelineYear {
  /** Calendar year being modelled. */
  year: number;
  /** Household age in that year (the older spouse, for a couple). */
  age: number;
  /** MAGI generated by the withdrawal plan before any conversion. */
  baseMAGI: number;
  /** MAGI ceiling for the year, from the FPL target. */
  targetMAGI: number;
  /** Room between base MAGI and the target — what can be converted. */
  headroom: number;
  /** Amount converted Traditional -> Roth this year. */
  conversion: number;
  /** Total MAGI including the conversion. */
  totalMAGI: number;
  /** Estimated federal tax on the converted amount. */
  conversionTaxCost: number;
  /** ACA subsidy at this MAGI. */
  annualSubsidy: number;
  /** Premium actually paid after subsidy. */
  netAnnualPremium: number;
  /** Year this conversion becomes accessible penalty-free. */
  accessibleIn: number;
  /** Traditional IRA balance at year end. */
  traditionalBalance: number;
  /** Roth balance at year end. */
  rothBalance: number;
  /** True once the household reaches Medicare age. */
  onMedicare: boolean;
}

export interface PipelineResult {
  years: PipelineYear[];
  assumptions: PipelineAssumptions;
  /** Total moved Traditional -> Roth across the projection. */
  totalConverted: number;
  /** Estimated federal tax paid on those conversions. */
  totalConversionTax: number;
  /** Total ACA subsidy retained across the projection. */
  totalSubsidy: number;
  /** Traditional IRA still remaining when Medicare begins. */
  traditionalRemainingAtMedicare: number;
  /** Years modelled before Medicare eligibility. */
  yearsToMedicare: number;
}

function fplFor(householdSize: number, yearsFromNow: number, inflationRate: number): number {
  const base = FPL_2026[householdSize] ?? FPL_2026[4];
  return base * Math.pow(1 + inflationRate, yearsFromNow);
}

/**
 * Project the conversion ladder from the current year until Medicare.
 *
 * @param profile      The household, as entered in the optimizer.
 * @param baseMAGI     MAGI the optimized withdrawal plan already generates.
 * @param startYear    Calendar year to start from.
 * @param maxYears     Cap on projection length, for display purposes.
 */
export function buildPipeline(
  profile: UserProfile,
  baseMAGI: number,
  startYear: number,
  maxYears = 10,
  assumptions: PipelineAssumptions = DEFAULT_ASSUMPTIONS
): PipelineResult {
  const yearsToMedicare = Math.max(0, MEDICARE_AGE - profile.age);
  const horizon = Math.max(1, Math.min(maxYears, yearsToMedicare));

  let traditionalBalance = profile.accounts.traditionalIRA;
  let rothBalance = profile.accounts.rothIRA;

  const years: PipelineYear[] = [];

  for (let i = 0; i < horizon; i++) {
    const age = profile.age + i;
    const year = startYear + i;
    const onMedicare = age >= MEDICARE_AGE;

    const fpl = fplFor(profile.householdSize, i, assumptions.inflationRate);
    const targetMAGI = fpl * (assumptions.targetFplPercentage / 100);

    // Base MAGI drifts with inflation alongside spending.
    const yearBaseMAGI = baseMAGI * Math.pow(1 + assumptions.inflationRate, i);

    // Convert into whatever room is left under the target, limited by what is
    // actually in the Traditional IRA. Past Medicare age the subsidy no longer
    // constrains anything, so the ladder stops.
    const headroom = onMedicare ? 0 : Math.max(0, targetMAGI - yearBaseMAGI);
    const conversion = Math.min(headroom, traditionalBalance);

    const totalMAGI = yearBaseMAGI + conversion;
    const subsidy = calculateACASubsidy(totalMAGI, {
      ...profile,
      age,
    });

    traditionalBalance = Math.max(0, (traditionalBalance - conversion) * (1 + assumptions.growthRate));
    rothBalance = (rothBalance + conversion) * (1 + assumptions.growthRate);

    years.push({
      year,
      age,
      baseMAGI: yearBaseMAGI,
      targetMAGI,
      headroom,
      conversion,
      totalMAGI,
      conversionTaxCost: conversion * assumptions.effectiveTaxRate,
      annualSubsidy: subsidy.annualSubsidy,
      netAnnualPremium: subsidy.netAnnualPremium,
      accessibleIn: year + ROTH_SEASONING_YEARS,
      traditionalBalance,
      rothBalance,
      onMedicare,
    });
  }

  return {
    years,
    assumptions,
    totalConverted: years.reduce((s, y) => s + y.conversion, 0),
    totalConversionTax: years.reduce((s, y) => s + y.conversionTaxCost, 0),
    totalSubsidy: years.reduce((s, y) => s + y.annualSubsidy, 0),
    traditionalRemainingAtMedicare: years.length ? years[years.length - 1].traditionalBalance : 0,
    yearsToMedicare,
  };
}

// ─── Annual Action Calendar ──────────────────────────────────────────────────

export type CalendarUrgency = "deadline" | "action" | "window";

export interface CalendarItem {
  /** Month index, 0 = January. */
  month: number;
  /** Short date label, e.g. "Dec 31". */
  when: string;
  title: string;
  detail: string;
  urgency: CalendarUrgency;
}

/**
 * The year's fixed decision points, with the household's own numbers written in.
 *
 * Open enrollment for 2027 coverage runs Nov 1 2026 – Jan 15 2027, with Dec 15
 * the cutoff for a January 1 start. Several state marketplaces run later
 * deadlines, and Idaho, Connecticut and Massachusetts open earlier — so the
 * enrollment entries note that state rules vary rather than asserting one date
 * for everyone.
 */
export function buildActionCalendar(
  targetMAGI: number,
  conversionHeadroom: number,
  formatMoney: (n: number) => string
): CalendarItem[] {
  return [
    {
      month: 0,
      when: "January",
      title: "Set this year's MAGI target",
      detail: `Re-run the optimizer against current balances. Your target is ${formatMoney(targetMAGI)} — every withdrawal decision this year measures against it.`,
      urgency: "action",
    },
    {
      month: 3,
      when: "April",
      title: "Reconcile last year's actual MAGI",
      detail:
        "Your filed return is the first hard confirmation of where MAGI actually landed. If it missed the target, this year's plan needs adjusting, not next year's.",
      urgency: "action",
    },
    {
      month: 6,
      when: "July",
      title: "Mid-year checkpoint",
      detail:
        "Half the year's income is realized. Unplanned dividends, capital gains distributions, or a part-time paycheck all move MAGI — check the running total against target while there is still room to correct.",
      urgency: "action",
    },
    {
      month: 9,
      when: "October",
      title: "Lock the conversion amount",
      detail: `Income for the year is nearly known, so the remaining headroom is now reliable. Modelled room for a Roth conversion: ${formatMoney(conversionHeadroom)}.`,
      urgency: "action",
    },
    {
      month: 10,
      when: "Nov 1",
      title: "Open enrollment begins",
      detail:
        "Enrollment for next year's coverage opens. Your MAGI estimate on the application determines the advance subsidy you receive all year. State marketplaces vary — a few open earlier.",
      urgency: "window",
    },
    {
      month: 11,
      when: "Dec 15",
      title: "Deadline for January 1 coverage",
      detail:
        "Enroll by this date for coverage starting January 1. Later enrollment is still possible in most states through mid-January, but coverage starts February 1.",
      urgency: "deadline",
    },
    {
      month: 11,
      when: "Dec 31",
      title: "Roth conversion deadline",
      detail:
        "A conversion counts for the tax year it is executed in, and there is no extension. Unlike an IRA contribution, this cannot be done retroactively in April.",
      urgency: "deadline",
    },
    {
      month: 11,
      when: "Dec 31",
      title: "MAGI locks",
      detail:
        "The year's income is final. Every subsidy dollar for this year is now determined and nothing further can change it.",
      urgency: "deadline",
    },
  ];
}
